version: "3.7"
x-logging:
  &default-logging
  logging:
    driver: json-file
    options:
      max-size: 100M

services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./certs:/etc/nginx/certs
      - ./vhost:/etc/nginx/vhost.d
      - ./html:/usr/share/nginx/html
  nginx-proxy-acme:
    image: nginxproxy/acme-companion
    container_name: nginx-proxy-acme
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./certs:/etc/nginx/certs
      - ./vhost:/etc/nginx/vhost.d
      - ./html:/usr/share/nginx/html
      - ./acme:/etc/acme.sh
    environment:
      - DEFAULT_EMAIL=jinting.zhou@mail.utoronto.ca
      - NGINX_PROXY_CONTAINER=nginx-proxy
  frontend:
    image: ghcr.io/utsc-cscc09-programming-on-the-web/frontend-project-cyj
    container_name: frontend
    restart: always
    expose:
      - 80
    environment:
      - VIRTUAL_HOST=beat.codes
      - LETSENCRYPT_HOST=beat.codes
  backend:
    image: ghcr.io/utsc-cscc09-programming-on-the-web/backend-project-cyj
    container_name: backend
    restart: always
    expose:
      - 3000
    environment:
      - VIRTUAL_HOST=api.beat.codes
      - LETSENCRYPT_HOST=api.beat.codes
  db:
    container_name: db
    image: postgres:16
    restart: always
    environment:
      POSTGRES_DB: $DB_NAME
      POSTGRES_USER: $DB_USER
      POSTGRES_PASSWORD: $DB_PASSWD
      PGUSER: $DB_USER
    volumes:
      - ./database-data:/var/lib/postgresql/data
    healthcheck:
      test: "pg_isready -h db"
      timeout: 10s
      retries: 10
  
  judge0:
    image: judge0/judge0:1.13.1
    volumes:
      - ./judge0.conf:/judge0.conf:ro
    expose:
      - 2358
    privileged: true
    <<: *default-logging
    restart: always
    environment:
      - VIRTUAL_HOST=judge0.beat.codes
      - LETSENCRYPT_HOST=judge0.beat.codes

  workers:
    image: judge0/judge0:1.13.1
    command: ["./scripts/workers"]
    volumes:
      - ./judge0.conf:/judge0.conf:ro
    privileged: true
    <<: *default-logging
    restart: always

  judge0db:
    container_name: judge0db
    image: postgres:16.2
    env_file: judge0.conf
    volumes:
      - data:/var/lib/postgresql/data/
    <<: *default-logging
    restart: always

  redis:
    image: redis:7.2.4
    command: [
      "bash", "-c",
      'docker-entrypoint.sh --appendonly no --requirepass "$$REDIS_PASSWORD"'
    ]
    env_file: judge0.conf
    <<: *default-logging
    restart: always

volumes:
  data:
